language: node_js
node_js:
  - 7
before_install:
  - npm i npm@^4 -g
  # travis specific configuration to convince shell having a screen
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
branches:
  only:
    - master
cache:
  yarn: true
  directories:
    - node_modules
