language: node_js
node_js:
  - 7
branches:
  only:
    - master
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - npm i npm@^4 -g
  # travis specific configuration to convince shell having a screen
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - npm install -g firebase-tools
script:
  - npm run build
after_success:
  - firebase deploy --token $FIREBASE_API_TOKEN
